In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
print(titanic)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [4]:
survival_rate = pd.pivot_table(titanic,values='survived',index=['class', 'sex'],columns='alone')
survival_rate

alone             False     True
class  sex
First  female  0.966667  0.970588
       male    0.425532  0.333333
Second female  0.931818  0.906250
       male    0.277778  0.097222
Third  female  0.416667  0.616667
       male    0.180723  0.121212

In [5]:
pd.pivot_table(titanic,values=['age', 'fare'],index='sex',columns='class',aggfunc='min')

         age                  fare
class  First Second Third    First Second Third
sex
female  2.00   2.00  0.75  25.9292   10.5  6.75
male    0.92   0.67  0.42   0.0000    0.0  0.00

In [6]:
data = {'department': ['CSE', 'CSE', 'CSE', 'CSE', 'AIML', 'AIML', 'AIML', 'AIML', 'ECE', 'ECE', 'ECE', 'ECE'],'gender': ['M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F'],'salary': [75000, 72000, 68000, 80000, 85000, 78000, 90000, 82000, 60000, 65000, 58000, 62000]
}
employees = pd.DataFrame(data)
print(employees)
print()

pd.pivot_table(employees,values='salary',index='gender',columns='department',aggfunc='mean')

   department gender  salary
0         CSE      M   75000
1         CSE      F   72000
2         CSE      M   68000
3         CSE      F   80000
4        AIML      M   85000
5        AIML      F   78000
6        AIML      M   90000
7        AIML      F   82000
8         ECE      M   60000
9         ECE      F   65000
10        ECE      M   58000
11        ECE      F   62000

department     AIML      CSE      ECE
gender
F           80000.0  76000.0  63500.0
M           87500.0  71500.0  59000.0

In [7]:
pd.pivot_table(employees,values='salary',index='gender',columns='department',aggfunc='count')

department  AIML  CSE  ECE
gender
F              2    2    2
M              2    2    2

In [8]:
pd.pivot_table(employees,values='salary',index='gender',columns='department',margins=True)

department     AIML      CSE      ECE           All
gender
F           80000.0  76000.0  63500.0  73166.666667
M           87500.0  71500.0  59000.0  72666.666667
All         83750.0  73750.0  61250.0  72916.666667

In [9]:

employees['age'] = [25, 28, 35, 42, 23, 55, 38, 31, 45, 27, 50, 33]


e1 = pd.cut(employees['age'],bins=[20, 30, 40, 60],labels=['Junior', 'Mid', 'Senior'])
pd.pivot_table(employees,values='salary',index=e1,columns='department')

department     AIML      CSE      ECE
age
Junior      85000.0  73500.0  65000.0
Mid         86000.0  68000.0  62000.0
Senior      78000.0  80000.0  59000.0

In [10]:
pd.pivot_table(employees,index='department',aggfunc={'salary': 'sum', 'age': 'mean'})

              age  salary
department
AIML        36.75  335000
CSE         32.50  295000
ECE         38.75  245000

In [12]:
pd.pivot_table(titanic, values='survived', index='sex', columns='class', margins=True)

class      First    Second     Third       All
sex
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838